apiVersion: orkestra.orkspace.io/v1
kind: Simulate
metadata:
  name: redis-sim
  description: Verify Redis headless Service, Service, and StatefulSet created in cycle 1

spec:
  katalog: ./katalog.yaml
  cr: ./cr.yaml
  cycles: 5

  expect:
    steady: true
    noErrors: true
    ops:
      - cycle: 1
        verb: create
        resource: services
        name: my-redis-redis-headless
      - cycle: 1
        verb: create
        resource: services
        name: my-redis-redis
      - cycle: 1
        verb: create
        resource: statefulsets
        name: my-redis-redis
