apiVersion: orkestra.orkspace.io/v1
kind: Simulate
metadata:
  name: postgres-sim
  description: Verify PostgreSQL credentials Secret, headless Service, Service, and StatefulSet created in cycle 1

spec:
  katalog: ./katalog.yaml
  cr: ./cr.yaml
  cycles: 5

  expect:
    steady: true
    noErrors: true
    ops:
      - cycle: 1
        verb: create
        resource: secrets
        name: my-postgres-creds
      - cycle: 1
        verb: create
        resource: services
        name: my-postgres-postgres-headless
      - cycle: 1
        verb: create
        resource: services
        name: my-postgres-postgres
      - cycle: 1
        verb: create
        resource: statefulsets
        name: my-postgres-postgres
