apiVersion: rabbitmq.orkestra.io/v1
kind: RabbitMQ
metadata:
  name: my-rabbitmq
  namespace: default
spec:
  version: "management"
  username: admin
  vhost: /
  storageSize: 5Gi
  storageClass: standard
  resourceProfile: small
  replicas: 1
