apiVersion: kafka.orkestra.io/v1
kind: Kafka
metadata:
  name: my-kafka
  namespace: default
spec:
  version: "latest"
  replicas: 1
  storageSize: 20Gi
  storageClass: standard
  resourceProfile: compute-heavy
